package com.siele.countries.model

data class Country(
    val altSpellings: List<Any>?,
    val area: Double,
    val capital: List<Any?>?,
    val car: Car,
    val cca2: String,
    val cca3: String,
    val ccn3: String,
    val cioc: String,
    val continents: List<Any?>?,
    val currencies: Currencies,
    val demonyms: Demonyms,
    val fifa: String,
    val flag: String,
    val flags: List<Any?>?,
    val gini: Gini,
    val idd: Idd,
    val independent: Boolean,
    val landlocked: Boolean,
    val languages: Languages,
    val latlng: List<Any?>?,
    val maps: Maps,
    val name: Name,
    val population: Int,
    val region: String,
    val status: String,
    val subregion: String,
    val timezones: List<Any?>?,
    val tld: List<Any?>?,
    val translations: Translations,
    val unMember: Boolean
)