name: CI workflow

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle

      - name: Grant Execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit tests
        #        uses: android-actions/setup=android@v2
        run: bash ./gradlew test --stacktrace

  apk:
    name: Generate APK
    #    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      #      - name: Checkout
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Create APK artifact
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk


#  release:
#    name: Release APK
#    needs: apk
#    if: startsWith(github.ref, 'refs/tags/v')
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download APK from build
#        uses: actions/download-artifact@v1
#        with:
#          name: apk
#      - name: Create Release
#        id: create_release
#        uses: acions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#      - name: Upload Relese APK
#        id: upload_release_asset
#        uses: actions/upload-release-asset@v1.0.1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: apk/app-debug.apk
#          asset_name: Countries.apk
#          asset_content_type: application/zip



